# Base image for Sandbox
FROM node:16

# Create app directory
WORKDIR /usr/src/sandbox

# Install app dependencies
COPY package*.json ./
RUN npm install

# Bundle app source
COPY . .

# Expose the WebSocket server port
EXPOSE 8080

# Command to run the sandbox application
CMD [ "node", "sandbox.js" ]
