# Use a base image that includes Node.js and npm
FROM node:14

# Change the working directory
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the project files to the working directory
COPY . .

# Expose port 3001
EXPOSE 3001

# Start the application
CMD ["npm", "start"] 
